# Generated by Django 3.1.2 on 2021-04-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='dateOfCreation',
        ),
        migrations.AddField(
            model_name='task',
            name='dateTimeOfCreation',
            field=models.DateField(auto_now=True),
        ),
    ]
