# Generated by Django 3.1.2 on 2021-04-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20210416_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateTimeOfCreation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
